package pojo;
// Generated Dec 9, 2013 5:11:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="clothingdb"
    , uniqueConstraints = @UniqueConstraint(columnNames="UserName") 
)
public class Account  implements java.io.Serializable {


     private Integer id;
     private String userName;
     private String password;
     private Set<Tradinghistory> tradinghistories = new HashSet<Tradinghistory>(0);

    public Account() {
    }

	
    public Account(String userName, String password) {
        this.userName = userName;
        this.password = password;
    }
    public Account(String userName, String password, Set<Tradinghistory> tradinghistories) {
       this.userName = userName;
       this.password = password;
       this.tradinghistories = tradinghistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="UserName", unique=true, nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="Password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="account")
    public Set<Tradinghistory> getTradinghistories() {
        return this.tradinghistories;
    }
    
    public void setTradinghistories(Set<Tradinghistory> tradinghistories) {
        this.tradinghistories = tradinghistories;
    }




}


