package pojo;
// Generated Dec 9, 2013 5:11:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="clothingdb"
    , uniqueConstraints = @UniqueConstraint(columnNames="Name") 
)
public class Category  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set<Clothing> clothings = new HashSet<Clothing>(0);

    public Category() {
    }

	
    public Category(String name) {
        this.name = name;
    }
    public Category(String name, Set<Clothing> clothings) {
       this.name = name;
       this.clothings = clothings;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="Name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="category")
    public Set<Clothing> getClothings() {
        return this.clothings;
    }
    
    public void setClothings(Set<Clothing> clothings) {
        this.clothings = clothings;
    }




}


