package pojo;
// Generated Dec 10, 2013 12:48:05 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChitietkythuatId generated by hbm2java
 */
@Embeddable
public class ChitietkythuatId  implements java.io.Serializable {


     private String masp;
     private String datdiem;

    public ChitietkythuatId() {
    }

    public ChitietkythuatId(String masp, String datdiem) {
       this.masp = masp;
       this.datdiem = datdiem;
    }
   

    @Column(name="MASP", nullable=false, length=20)
    public String getMasp() {
        return this.masp;
    }
    
    public void setMasp(String masp) {
        this.masp = masp;
    }

    @Column(name="DATDIEM", nullable=false, length=100)
    public String getDatdiem() {
        return this.datdiem;
    }
    
    public void setDatdiem(String datdiem) {
        this.datdiem = datdiem;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChitietkythuatId) ) return false;
		 ChitietkythuatId castOther = ( ChitietkythuatId ) other; 
         
		 return ( (this.getMasp()==castOther.getMasp()) || ( this.getMasp()!=null && castOther.getMasp()!=null && this.getMasp().equals(castOther.getMasp()) ) )
 && ( (this.getDatdiem()==castOther.getDatdiem()) || ( this.getDatdiem()!=null && castOther.getDatdiem()!=null && this.getDatdiem().equals(castOther.getDatdiem()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMasp() == null ? 0 : this.getMasp().hashCode() );
         result = 37 * result + ( getDatdiem() == null ? 0 : this.getDatdiem().hashCode() );
         return result;
   }   


}


