package pojo;
// Generated Dec 9, 2013 5:11:35 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clothing generated by hbm2java
 */
@Entity
@Table(name="clothing"
    ,catalog="clothingdb"
)
public class Clothing  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String name;
     private int price;
     private int quantity;
     private String image;
     private Set<Tradinghistory> tradinghistories = new HashSet<Tradinghistory>(0);

    public Clothing() {
    }

	
    public Clothing(String name, int price, int quantity) {
        this.name = name;
        this.price = price;
        this.quantity = quantity;
    }
    public Clothing(Category category, String name, int price, int quantity, String image, Set<Tradinghistory> tradinghistories) {
       this.category = category;
       this.name = name;
       this.price = price;
       this.quantity = quantity;
       this.image = image;
       this.tradinghistories = tradinghistories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Category_Id")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="Price", nullable=false)
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    
    @Column(name="Image", length=2000)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="clothing")
    public Set<Tradinghistory> getTradinghistories() {
        return this.tradinghistories;
    }
    
    public void setTradinghistories(Set<Tradinghistory> tradinghistories) {
        this.tradinghistories = tradinghistories;
    }




}


