package pojo;
// Generated Dec 10, 2013 12:48:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ctkhuyenmai generated by hbm2java
 */
@Entity
@Table(name="ctkhuyenmai"
    ,catalog="dbbestbuy"
)
public class Ctkhuyenmai  implements java.io.Serializable {


     private String mact;
     private Date ngaybatdau;
     private Date ngayketthuc;
     private String thongtinchung;
     private Set<Khuyenmai> khuyenmais = new HashSet<Khuyenmai>(0);

    public Ctkhuyenmai() {
    }

	
    public Ctkhuyenmai(String mact) {
        this.mact = mact;
    }
    public Ctkhuyenmai(String mact, Date ngaybatdau, Date ngayketthuc, String thongtinchung, Set<Khuyenmai> khuyenmais) {
       this.mact = mact;
       this.ngaybatdau = ngaybatdau;
       this.ngayketthuc = ngayketthuc;
       this.thongtinchung = thongtinchung;
       this.khuyenmais = khuyenmais;
    }
   
     @Id 
    
    @Column(name="MACT", unique=true, nullable=false, length=20)
    public String getMact() {
        return this.mact;
    }
    
    public void setMact(String mact) {
        this.mact = mact;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="NGAYBATDAU", length=10)
    public Date getNgaybatdau() {
        return this.ngaybatdau;
    }
    
    public void setNgaybatdau(Date ngaybatdau) {
        this.ngaybatdau = ngaybatdau;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="NGAYKETTHUC", length=10)
    public Date getNgayketthuc() {
        return this.ngayketthuc;
    }
    
    public void setNgayketthuc(Date ngayketthuc) {
        this.ngayketthuc = ngayketthuc;
    }
    
    @Column(name="THONGTINCHUNG", length=4000)
    public String getThongtinchung() {
        return this.thongtinchung;
    }
    
    public void setThongtinchung(String thongtinchung) {
        this.thongtinchung = thongtinchung;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="ctkhuyenmai")
    public Set<Khuyenmai> getKhuyenmais() {
        return this.khuyenmais;
    }
    
    public void setKhuyenmais(Set<Khuyenmai> khuyenmais) {
        this.khuyenmais = khuyenmais;
    }




}


