package pojo;
// Generated Dec 10, 2013 12:48:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hangsanxuat generated by hbm2java
 */
@Entity
@Table(name="hangsanxuat"
    ,catalog="dbbestbuy"
)
public class Hangsanxuat  implements java.io.Serializable {


     private String mahsx;
     private String tenhsx;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Hangsanxuat() {
    }

	
    public Hangsanxuat(String mahsx) {
        this.mahsx = mahsx;
    }
    public Hangsanxuat(String mahsx, String tenhsx, Set<Sanpham> sanphams) {
       this.mahsx = mahsx;
       this.tenhsx = tenhsx;
       this.sanphams = sanphams;
    }
   
     @Id 
    
    @Column(name="MAHSX", unique=true, nullable=false, length=20)
    public String getMahsx() {
        return this.mahsx;
    }
    
    public void setMahsx(String mahsx) {
        this.mahsx = mahsx;
    }
    
    @Column(name="TENHSX", length=50)
    public String getTenhsx() {
        return this.tenhsx;
    }
    
    public void setTenhsx(String tenhsx) {
        this.tenhsx = tenhsx;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="hangsanxuat")
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


