package pojo;
// Generated Dec 10, 2013 12:48:05 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Khuyenmai generated by hbm2java
 */
@Entity
@Table(name="khuyenmai"
    ,catalog="dbbestbuy"
)
public class Khuyenmai  implements java.io.Serializable {


     private String makm;
     private Ctkhuyenmai ctkhuyenmai;
     private Date ngaybatdau;
     private Date ngayketthuc;
     private Float giakm;
     private String thongtinkhuyenmai;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Khuyenmai() {
    }

	
    public Khuyenmai(String makm) {
        this.makm = makm;
    }
    public Khuyenmai(String makm, Ctkhuyenmai ctkhuyenmai, Date ngaybatdau, Date ngayketthuc, Float giakm, String thongtinkhuyenmai, Set<Sanpham> sanphams) {
       this.makm = makm;
       this.ctkhuyenmai = ctkhuyenmai;
       this.ngaybatdau = ngaybatdau;
       this.ngayketthuc = ngayketthuc;
       this.giakm = giakm;
       this.thongtinkhuyenmai = thongtinkhuyenmai;
       this.sanphams = sanphams;
    }
   
     @Id 
    
    @Column(name="MAKM", unique=true, nullable=false, length=20)
    public String getMakm() {
        return this.makm;
    }
    
    public void setMakm(String makm) {
        this.makm = makm;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CTKMAI")
    public Ctkhuyenmai getCtkhuyenmai() {
        return this.ctkhuyenmai;
    }
    
    public void setCtkhuyenmai(Ctkhuyenmai ctkhuyenmai) {
        this.ctkhuyenmai = ctkhuyenmai;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="NGAYBATDAU", length=10)
    public Date getNgaybatdau() {
        return this.ngaybatdau;
    }
    
    public void setNgaybatdau(Date ngaybatdau) {
        this.ngaybatdau = ngaybatdau;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="NGAYKETTHUC", length=10)
    public Date getNgayketthuc() {
        return this.ngayketthuc;
    }
    
    public void setNgayketthuc(Date ngayketthuc) {
        this.ngayketthuc = ngayketthuc;
    }
    
    @Column(name="GIAKM", precision=12, scale=0)
    public Float getGiakm() {
        return this.giakm;
    }
    
    public void setGiakm(Float giakm) {
        this.giakm = giakm;
    }
    
    @Column(name="THONGTINKHUYENMAI", length=4000)
    public String getThongtinkhuyenmai() {
        return this.thongtinkhuyenmai;
    }
    
    public void setThongtinkhuyenmai(String thongtinkhuyenmai) {
        this.thongtinkhuyenmai = thongtinkhuyenmai;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="khuyenmai")
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


