package pojo;
// Generated Dec 10, 2013 12:48:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaisanpham generated by hbm2java
 */
@Entity
@Table(name="loaisanpham"
    ,catalog="dbbestbuy"
)
public class Loaisanpham  implements java.io.Serializable {


     private String maloai;
     private String tenloai;
     private Set<Sanpham> sanphams = new HashSet<Sanpham>(0);

    public Loaisanpham() {
    }

	
    public Loaisanpham(String maloai) {
        this.maloai = maloai;
    }
    public Loaisanpham(String maloai, String tenloai, Set<Sanpham> sanphams) {
       this.maloai = maloai;
       this.tenloai = tenloai;
       this.sanphams = sanphams;
    }
   
     @Id 
    
    @Column(name="MALOAI", unique=true, nullable=false, length=20)
    public String getMaloai() {
        return this.maloai;
    }
    
    public void setMaloai(String maloai) {
        this.maloai = maloai;
    }
    
    @Column(name="TENLOAI", length=50)
    public String getTenloai() {
        return this.tenloai;
    }
    
    public void setTenloai(String tenloai) {
        this.tenloai = tenloai;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="loaisanpham")
    public Set<Sanpham> getSanphams() {
        return this.sanphams;
    }
    
    public void setSanphams(Set<Sanpham> sanphams) {
        this.sanphams = sanphams;
    }




}


