package pojo;
// Generated Dec 10, 2013 12:48:05 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sanpham generated by hbm2java
 */
@Entity
@Table(name="sanpham"
    ,catalog="dbbestbuy"
)
public class Sanpham  implements java.io.Serializable {


     private String masp;
     private Khuyenmai khuyenmai;
     private Loaisanpham loaisanpham;
     private Hangsanxuat hangsanxuat;
     private String tensp;
     private Float gia;
     private Integer soluongcon;
     private String hinhanh;
     private Boolean laspnoibat;
     private Float diem;
     private Set<Sanpham> sanphamsForMasp = new HashSet<Sanpham>(0);
     private Set<Sanpham> sanphamsForMapk = new HashSet<Sanpham>(0);
     private Set<Chitietphieudat> chitietphieudats = new HashSet<Chitietphieudat>(0);
     private Set<Chitietkythuat> chitietkythuats = new HashSet<Chitietkythuat>(0);

    public Sanpham() {
    }

	
    public Sanpham(String masp) {
        this.masp = masp;
    }
    public Sanpham(String masp, Khuyenmai khuyenmai, Loaisanpham loaisanpham, Hangsanxuat hangsanxuat, String tensp, Float gia, Integer soluongcon, String hinhanh, Boolean laspnoibat, Float diem, Set<Sanpham> sanphamsForMasp, Set<Sanpham> sanphamsForMapk, Set<Chitietphieudat> chitietphieudats, Set<Chitietkythuat> chitietkythuats) {
       this.masp = masp;
       this.khuyenmai = khuyenmai;
       this.loaisanpham = loaisanpham;
       this.hangsanxuat = hangsanxuat;
       this.tensp = tensp;
       this.gia = gia;
       this.soluongcon = soluongcon;
       this.hinhanh = hinhanh;
       this.laspnoibat = laspnoibat;
       this.diem = diem;
       this.sanphamsForMasp = sanphamsForMasp;
       this.sanphamsForMapk = sanphamsForMapk;
       this.chitietphieudats = chitietphieudats;
       this.chitietkythuats = chitietkythuats;
    }
   
     @Id 
    
    @Column(name="MASP", unique=true, nullable=false, length=20)
    public String getMasp() {
        return this.masp;
    }
    
    public void setMasp(String masp) {
        this.masp = masp;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="KHUYENMAI")
    public Khuyenmai getKhuyenmai() {
        return this.khuyenmai;
    }
    
    public void setKhuyenmai(Khuyenmai khuyenmai) {
        this.khuyenmai = khuyenmai;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="LOAISP")
    public Loaisanpham getLoaisanpham() {
        return this.loaisanpham;
    }
    
    public void setLoaisanpham(Loaisanpham loaisanpham) {
        this.loaisanpham = loaisanpham;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="HANGSX")
    public Hangsanxuat getHangsanxuat() {
        return this.hangsanxuat;
    }
    
    public void setHangsanxuat(Hangsanxuat hangsanxuat) {
        this.hangsanxuat = hangsanxuat;
    }
    
    @Column(name="TENSP", length=200)
    public String getTensp() {
        return this.tensp;
    }
    
    public void setTensp(String tensp) {
        this.tensp = tensp;
    }
    
    @Column(name="GIA", precision=12, scale=0)
    public Float getGia() {
        return this.gia;
    }
    
    public void setGia(Float gia) {
        this.gia = gia;
    }
    
    @Column(name="SOLUONGCON")
    public Integer getSoluongcon() {
        return this.soluongcon;
    }
    
    public void setSoluongcon(Integer soluongcon) {
        this.soluongcon = soluongcon;
    }
    
    @Column(name="HINHANH", length=50)
    public String getHinhanh() {
        return this.hinhanh;
    }
    
    public void setHinhanh(String hinhanh) {
        this.hinhanh = hinhanh;
    }
    
    @Column(name="LASPNOIBAT")
    public Boolean getLaspnoibat() {
        return this.laspnoibat;
    }
    
    public void setLaspnoibat(Boolean laspnoibat) {
        this.laspnoibat = laspnoibat;
    }
    
    @Column(name="DIEM", precision=12, scale=0)
    public Float getDiem() {
        return this.diem;
    }
    
    public void setDiem(Float diem) {
        this.diem = diem;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sanphamsForMapk")
    public Set<Sanpham> getSanphamsForMasp() {
        return this.sanphamsForMasp;
    }
    
    public void setSanphamsForMasp(Set<Sanpham> sanphamsForMasp) {
        this.sanphamsForMasp = sanphamsForMasp;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sanphamsForMasp")
    public Set<Sanpham> getSanphamsForMapk() {
        return this.sanphamsForMapk;
    }
    
    public void setSanphamsForMapk(Set<Sanpham> sanphamsForMapk) {
        this.sanphamsForMapk = sanphamsForMapk;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sanpham")
    public Set<Chitietphieudat> getChitietphieudats() {
        return this.chitietphieudats;
    }
    
    public void setChitietphieudats(Set<Chitietphieudat> chitietphieudats) {
        this.chitietphieudats = chitietphieudats;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sanpham")
    public Set<Chitietkythuat> getChitietkythuats() {
        return this.chitietkythuats;
    }
    
    public void setChitietkythuats(Set<Chitietkythuat> chitietkythuats) {
        this.chitietkythuats = chitietkythuats;
    }




}


