package pojo;
// Generated Dec 10, 2013 12:48:05 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaikhoanDangnhap generated by hbm2java
 */
@Entity
@Table(name="taikhoan_dangnhap"
    ,catalog="dbbestbuy"
)
public class TaikhoanDangnhap  implements java.io.Serializable {


     private String username;
     private Thanhvien thanhvien;
     private String password;
     private String roles;

    public TaikhoanDangnhap() {
    }

	
    public TaikhoanDangnhap(String username) {
        this.username = username;
    }
    public TaikhoanDangnhap(String username, Thanhvien thanhvien, String password, String roles) {
       this.username = username;
       this.thanhvien = thanhvien;
       this.password = password;
       this.roles = roles;
    }
   
     @Id 
    
    @Column(name="USERNAME", unique=true, nullable=false, length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MATV")
    public Thanhvien getThanhvien() {
        return this.thanhvien;
    }
    
    public void setThanhvien(Thanhvien thanhvien) {
        this.thanhvien = thanhvien;
    }
    
    @Column(name="PASSWORD", length=20)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="ROLES", length=12)
    public String getRoles() {
        return this.roles;
    }
    
    public void setRoles(String roles) {
        this.roles = roles;
    }




}


