package pojo;
// Generated Dec 9, 2013 5:11:35 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tradinghistory generated by hbm2java
 */
@Entity
@Table(name="tradinghistory"
    ,catalog="clothingdb"
)
public class Tradinghistory  implements java.io.Serializable {


     private Integer id;
     private Clothing clothing;
     private Account account;
     private int quantity;
     private Date time;

    public Tradinghistory() {
    }

    public Tradinghistory(Clothing clothing, Account account, int quantity, Date time) {
       this.clothing = clothing;
       this.account = account;
       this.quantity = quantity;
       this.time = time;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Clothing_Id", nullable=false)
    public Clothing getClothing() {
        return this.clothing;
    }
    
    public void setClothing(Clothing clothing) {
        this.clothing = clothing;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Account_Id", nullable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    
    @Column(name="Quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Time", nullable=false, length=19)
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }




}


